// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface InventoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.InventoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string InventoryID = 1;</code>
   */
  java.lang.String getInventoryID();
  /**
   * <code>string InventoryID = 1;</code>
   */
  com.google.protobuf.ByteString
      getInventoryIDBytes();

  /**
   * <code>string InventoryID1 = 12;</code>
   */
  java.lang.String getInventoryID1();
  /**
   * <code>string InventoryID1 = 12;</code>
   */
  com.google.protobuf.ByteString
      getInventoryID1Bytes();
}
