// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

/**
 * Protobuf type {@code inventory.InventoryRequest}
 */
public  final class InventoryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:inventory.InventoryRequest)
    InventoryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryRequest.newBuilder() to construct.
  private InventoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryRequest() {
    inventoryID_ = "";
    inventoryID1_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            inventoryID_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            inventoryID1_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return example.myapp.inventory.grpc.InventoryProto.internal_static_inventory_InventoryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return example.myapp.inventory.grpc.InventoryProto.internal_static_inventory_InventoryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            example.myapp.inventory.grpc.InventoryRequest.class, example.myapp.inventory.grpc.InventoryRequest.Builder.class);
  }

  public static final int INVENTORYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object inventoryID_;
  /**
   * <code>string InventoryID = 1;</code>
   */
  public java.lang.String getInventoryID() {
    java.lang.Object ref = inventoryID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inventoryID_ = s;
      return s;
    }
  }
  /**
   * <code>string InventoryID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getInventoryIDBytes() {
    java.lang.Object ref = inventoryID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inventoryID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVENTORYID1_FIELD_NUMBER = 12;
  private volatile java.lang.Object inventoryID1_;
  /**
   * <code>string InventoryID1 = 12;</code>
   */
  public java.lang.String getInventoryID1() {
    java.lang.Object ref = inventoryID1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inventoryID1_ = s;
      return s;
    }
  }
  /**
   * <code>string InventoryID1 = 12;</code>
   */
  public com.google.protobuf.ByteString
      getInventoryID1Bytes() {
    java.lang.Object ref = inventoryID1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inventoryID1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getInventoryIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, inventoryID_);
    }
    if (!getInventoryID1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, inventoryID1_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getInventoryIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, inventoryID_);
    }
    if (!getInventoryID1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, inventoryID1_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof example.myapp.inventory.grpc.InventoryRequest)) {
      return super.equals(obj);
    }
    example.myapp.inventory.grpc.InventoryRequest other = (example.myapp.inventory.grpc.InventoryRequest) obj;

    boolean result = true;
    result = result && getInventoryID()
        .equals(other.getInventoryID());
    result = result && getInventoryID1()
        .equals(other.getInventoryID1());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVENTORYID_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryID().hashCode();
    hash = (37 * hash) + INVENTORYID1_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryID1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(example.myapp.inventory.grpc.InventoryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code inventory.InventoryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:inventory.InventoryRequest)
      example.myapp.inventory.grpc.InventoryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.myapp.inventory.grpc.InventoryProto.internal_static_inventory_InventoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.myapp.inventory.grpc.InventoryProto.internal_static_inventory_InventoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.myapp.inventory.grpc.InventoryRequest.class, example.myapp.inventory.grpc.InventoryRequest.Builder.class);
    }

    // Construct using example.myapp.inventory.grpc.InventoryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      inventoryID_ = "";

      inventoryID1_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return example.myapp.inventory.grpc.InventoryProto.internal_static_inventory_InventoryRequest_descriptor;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRequest getDefaultInstanceForType() {
      return example.myapp.inventory.grpc.InventoryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRequest build() {
      example.myapp.inventory.grpc.InventoryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRequest buildPartial() {
      example.myapp.inventory.grpc.InventoryRequest result = new example.myapp.inventory.grpc.InventoryRequest(this);
      result.inventoryID_ = inventoryID_;
      result.inventoryID1_ = inventoryID1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof example.myapp.inventory.grpc.InventoryRequest) {
        return mergeFrom((example.myapp.inventory.grpc.InventoryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(example.myapp.inventory.grpc.InventoryRequest other) {
      if (other == example.myapp.inventory.grpc.InventoryRequest.getDefaultInstance()) return this;
      if (!other.getInventoryID().isEmpty()) {
        inventoryID_ = other.inventoryID_;
        onChanged();
      }
      if (!other.getInventoryID1().isEmpty()) {
        inventoryID1_ = other.inventoryID1_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      example.myapp.inventory.grpc.InventoryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (example.myapp.inventory.grpc.InventoryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object inventoryID_ = "";
    /**
     * <code>string InventoryID = 1;</code>
     */
    public java.lang.String getInventoryID() {
      java.lang.Object ref = inventoryID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inventoryID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string InventoryID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInventoryIDBytes() {
      java.lang.Object ref = inventoryID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inventoryID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string InventoryID = 1;</code>
     */
    public Builder setInventoryID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inventoryID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string InventoryID = 1;</code>
     */
    public Builder clearInventoryID() {
      
      inventoryID_ = getDefaultInstance().getInventoryID();
      onChanged();
      return this;
    }
    /**
     * <code>string InventoryID = 1;</code>
     */
    public Builder setInventoryIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inventoryID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inventoryID1_ = "";
    /**
     * <code>string InventoryID1 = 12;</code>
     */
    public java.lang.String getInventoryID1() {
      java.lang.Object ref = inventoryID1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inventoryID1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string InventoryID1 = 12;</code>
     */
    public com.google.protobuf.ByteString
        getInventoryID1Bytes() {
      java.lang.Object ref = inventoryID1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inventoryID1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string InventoryID1 = 12;</code>
     */
    public Builder setInventoryID1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inventoryID1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string InventoryID1 = 12;</code>
     */
    public Builder clearInventoryID1() {
      
      inventoryID1_ = getDefaultInstance().getInventoryID1();
      onChanged();
      return this;
    }
    /**
     * <code>string InventoryID1 = 12;</code>
     */
    public Builder setInventoryID1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inventoryID1_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:inventory.InventoryRequest)
  }

  // @@protoc_insertion_point(class_scope:inventory.InventoryRequest)
  private static final example.myapp.inventory.grpc.InventoryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new example.myapp.inventory.grpc.InventoryRequest();
  }

  public static example.myapp.inventory.grpc.InventoryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryRequest>
      PARSER = new com.google.protobuf.AbstractParser<InventoryRequest>() {
    @java.lang.Override
    public InventoryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public example.myapp.inventory.grpc.InventoryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

