// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface InventoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.InventoryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string InventoryID = 1;</code>
   */
  java.lang.String getInventoryID();
  /**
   * <code>string InventoryID = 1;</code>
   */
  com.google.protobuf.ByteString
      getInventoryIDBytes();

  /**
   * <code>string Name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string Description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int64 UnitPrice = 4;</code>
   */
  long getUnitPrice();

  /**
   * <code>int64 QuantityInStock = 5;</code>
   */
  long getQuantityInStock();

  /**
   * <code>int64 InventoryValue = 6;</code>
   */
  long getInventoryValue();

  /**
   * <code>int64 ReOrderValue = 7;</code>
   */
  long getReOrderValue();

  /**
   * <code>int64 ReOrderTime = 8;</code>
   */
  long getReOrderTime();

  /**
   * <code>int64 QuantityInReorder = 9;</code>
   */
  long getQuantityInReorder();

  /**
   * <code>bool DisContinued = 10;</code>
   */
  boolean getDisContinued();
}
