// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public final class InventoryProto {
  private InventoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_InventoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_InventoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_InventoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_InventoryReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\tinventory\"=\n\020Inventor" +
      "yRequest\022\023\n\013InventoryID\030\001 \001(\t\022\024\n\014Invento" +
      "ryID1\030\014 \001(\t\"\350\001\n\016InventoryReply\022\023\n\013Invent" +
      "oryID\030\001 \001(\t\022\014\n\004Name\030\002 \001(\t\022\023\n\013Description" +
      "\030\003 \001(\t\022\021\n\tUnitPrice\030\004 \001(\003\022\027\n\017QuantityInS" +
      "tock\030\005 \001(\003\022\026\n\016InventoryValue\030\006 \001(\003\022\024\n\014Re" +
      "OrderValue\030\007 \001(\003\022\023\n\013ReOrderTime\030\010 \001(\003\022\031\n" +
      "\021QuantityInReorder\030\t \001(\003\022\024\n\014DisContinued" +
      "\030\n \001(\0102T\n\020InventoryService\022@\n\006Search\022\033.i" +
      "nventory.InventoryRequest\032\031.inventory.In" +
      "ventoryReply2[\n\025InventoryRecordSearch\022B\n" +
      "\010ReSearch\022\033.inventory.InventoryRequest\032\031" +
      ".inventory.InventoryReplyB0\n\034example.mya" +
      "pp.inventory.grpcB\016InventoryProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_inventory_InventoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_InventoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_InventoryRequest_descriptor,
        new java.lang.String[] { "InventoryID", "InventoryID1", });
    internal_static_inventory_InventoryReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_InventoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_InventoryReply_descriptor,
        new java.lang.String[] { "InventoryID", "Name", "Description", "UnitPrice", "QuantityInStock", "InventoryValue", "ReOrderValue", "ReOrderTime", "QuantityInReorder", "DisContinued", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
